// Generated by scripts/vendor-launchmynft-solana.mjs — do not edit
window.ownerId = "97uZrxmqnvDAYPNNoKy5BWKJMmsupEvmMU1y25gdtpwZ";
window.collectionId = "LqSoiJ03DsNA8heEA6iT";
window.rpcEndpoint = "https://mainnet.helius-rpc.com/?api-key=218ab1d8-5f13-44e7-a2da-610c40d1b8cb";
